apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ignition-sync-operator.fullname" . }}-agent
  labels:
    {{- include "ignition-sync-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["sync.ignition.io"]
    resources: ["ignitionsyncs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["sync.ignition.io"]
    resources: ["syncprofiles"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
