{{- if .Values.injection.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "ignition-sync-operator.fullname" . }}-pod-injection
  labels:
    {{- include "ignition-sync-operator.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "ignition-sync-operator.fullname" . }}-webhook-cert
  {{- end }}
webhooks:
  - name: pod-inject.sync.ignition.io
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "ignition-sync-operator.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-v1-pod
    failurePolicy: Ignore
    matchPolicy: Equivalent
    reinvocationPolicy: IfNeeded
    namespaceSelector:
      matchExpressions:
        - key: ignition-sync.io/injection
          operator: In
          values: ["enabled"]
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 10
{{- end }}
