{{- if and .Values.injection.enabled .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ignition-sync-operator.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ignition-sync-operator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "ignition-sync-operator.fullname" . }}-webhook-cert
  dnsNames:
    - {{ include "ignition-sync-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "ignition-sync-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "ignition-sync-operator.fullname" . }}-selfsigned-issuer
    kind: Issuer
{{- end }}
