apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stoker-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stoker-operator.labels" . | nindent 4 }}
