apiVersion: v2
name: stoker-operator
description: Kubernetes operator that syncs Ignition gateway projects from a Git repository
type: application
version: 0.2.0
appVersion: "0.2.0"
kubeVersion: ">= 1.28.0"
home: https://github.com/ia-eknorr/stoker-operator
icon: https://raw.githubusercontent.com/ia-eknorr/stoker-operator/main/docs/static/img/logo.png
keywords:
  - ignition
  - stoker
  - gitops
  - operator
  - sync
