# This rule is not used by the project ignition-sync-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to sync.ignition.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ignition-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: ignitionsync-viewer-role
rules:
- apiGroups:
  - sync.ignition.io
  resources:
  - ignitionsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.ignition.io
  resources:
  - ignitionsyncs/status
  verbs:
  - get
