# This rule is not used by the project stoker-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to stoker.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: stoker-operator
    app.kubernetes.io/managed-by: kustomize
  name: stoker-viewer-role
rules:
- apiGroups:
  - stoker.io
  resources:
  - stokers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stoker.io
  resources:
  - stokers/status
  verbs:
  - get
