apiVersion: stoker.io/v1alpha1
kind: SyncProfile
metadata:
  name: syncprofile-sample
spec:
  mappings:
    - source: "projects/"
      destination: "projects/"
      type: dir
      required: true
    - source: "config/tags/"
      destination: "tags/"
      type: dir
  syncPeriod: 30
