apiVersion: sync.ignition.io/v1alpha1
kind: IgnitionSync
metadata:
  labels:
    app.kubernetes.io/name: ignition-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: ignitionsync-sample
spec:
  git:
    repo: "git@github.com:example-org/ignition-config.git"
    ref: "main"
    auth:
      sshKey:
        secretRef:
          name: "git-sync-secret"
          key: "ssh-privatekey"
  gateway:
    apiKeySecretRef:
      name: "ignition-api-key"
      key: "apiKey"
